[package]
name = "jsonlint"
version = "0.2.0"
authors = ["Manfred Lotz <manfred.lotz@yahoo.de>"]
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
clap_complete = "4.0"
serde_json = "1.0"
serde = "1.0"
